"""JavaScript generator for custom scrollbar interaction (drag thumb, click track, position sync)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/js/scrollbar.ipynb.

# %% auto #0
__all__ = ['generate_scrollbar_js']

# %% ../../nbs/js/scrollbar.ipynb #b2c2780b
from ..core.models import ScrollbarIds

# %% ../../nbs/js/scrollbar.ipynb #323652be
def generate_scrollbar_js(
    ids: ScrollbarIds,           # Scrollbar HTML IDs (track, thumb)
    position_input_id: str,      # ID of hidden input carrying current position
    nav_url: str,                # URL to POST target index to
    nav_param: str = "target_index",  # Parameter name for the index value
) -> str:  # JavaScript IIFE code fragment
    """Generate JS for scrollbar: thumb positioning from hidden input + drag/click interaction."""
    return f"""
        // === Virtual Scrollbar ({ids.prefix}) ===
        (function() {{
            let _isDragging = false;
            let _lastNavIndex = -1;

            function _getTrack() {{ return document.getElementById('{ids.track}'); }}
            function _getThumb() {{ return document.getElementById('{ids.thumb}'); }}
            function _getPositionInput() {{ return document.getElementById('{position_input_id}'); }}

            function _getMaxPosition(track) {{
                // Read max position from data attribute (set by server render).
                // Defaults to totalItems - visibleCount if not present.
                if (track.dataset.maxPosition !== undefined) {{
                    return parseInt(track.dataset.maxPosition);
                }}
                const totalItems = parseInt(track.dataset.totalItems || '0');
                const visibleCount = parseInt(track.dataset.visibleCount || '1');
                return Math.max(0, totalItems - visibleCount);
            }}

            function _positionThumbFromState() {{
                // Read state from DOM and position thumb via direct style manipulation.
                // Called after each HTMX settle — the hidden input carries the latest position.
                const track = _getTrack();
                const thumb = _getThumb();
                const input = _getPositionInput();
                if (!track || !thumb || !input) return;

                const totalItems = parseInt(track.dataset.totalItems || '0');
                const visibleCount = parseInt(track.dataset.visibleCount || '1');
                const position = parseInt(input.value || '0');

                if (totalItems <= 0 || visibleCount >= totalItems) {{
                    thumb.style.top = '0%';
                    thumb.style.height = '100%';
                    return;
                }}

                const thumbHeightPct = Math.max(
                    (visibleCount / totalItems) * 100,
                    (track.offsetHeight > 0) ? (24 / track.offsetHeight) * 100 : 4
                );
                const maxPos = Math.max(1, _getMaxPosition(track));
                const thumbTopPct = (position / maxPos) * (100 - thumbHeightPct);

                thumb.style.top = thumbTopPct.toFixed(2) + '%';
                thumb.style.height = thumbHeightPct.toFixed(2) + '%';
            }}

            function _calcTargetIndex(pointerY) {{
                const track = _getTrack();
                if (!track) return 0;
                const rect = track.getBoundingClientRect();
                const maxPos = Math.max(0, _getMaxPosition(track));
                const relY = Math.max(0, Math.min(pointerY - rect.top, rect.height));
                return Math.round((relY / rect.height) * maxPos);
            }}

            function _updateThumbPosition(pointerY) {{
                // Direct DOM update for real-time visual feedback during drag
                const track = _getTrack();
                const thumb = _getThumb();
                if (!track || !thumb) return;
                const rect = track.getBoundingClientRect();
                const thumbHeight = thumb.offsetHeight;
                const maxTop = rect.height - thumbHeight;
                const relY = Math.max(0, Math.min(pointerY - rect.top - thumbHeight / 2, maxTop));
                thumb.style.top = relY + 'px';
            }}

            function _navToIndex(index) {{
                if (index === _lastNavIndex) return;  // Deduplicate
                _lastNavIndex = index;
                htmx.ajax('POST', '{nav_url}', {{
                    swap: 'none',
                    values: {{ {nav_param}: index }}
                }});
            }}

            // --- Document-level drag handlers ---

            function _onDragMove(evt) {{
                if (!_isDragging) return;
                evt.preventDefault();
                _updateThumbPosition(evt.clientY);
                const index = _calcTargetIndex(evt.clientY);
                _navToIndex(index);
            }}

            function _onDragEnd(evt) {{
                if (!_isDragging) return;
                _isDragging = false;
                _lastNavIndex = -1;
                document.removeEventListener('pointermove', _onDragMove);
                document.removeEventListener('pointerup', _onDragEnd);
                document.removeEventListener('pointercancel', _onDragEnd);
                const thumb = _getThumb();
                if (thumb) thumb.style.cursor = '';
                _setupScrollbar();
            }}

            function _setupScrollbar() {{
                const track = _getTrack();
                const thumb = _getThumb();
                if (!track || !thumb) return;

                if (track._scrollbarAbort) track._scrollbarAbort.abort();
                const controller = new AbortController();
                track._scrollbarAbort = controller;
                const opts = {{ signal: controller.signal }};

                // --- Thumb drag start ---
                thumb.addEventListener('pointerdown', function(evt) {{
                    if (evt.button !== 0) return;
                    evt.preventDefault();
                    evt.stopPropagation();
                    _isDragging = true;
                    _lastNavIndex = -1;
                    thumb.style.cursor = 'grabbing';
                    document.addEventListener('pointermove', _onDragMove);
                    document.addEventListener('pointerup', _onDragEnd);
                    document.addEventListener('pointercancel', _onDragEnd);
                }}, opts);

                // --- Track click (jump to position) ---
                track.addEventListener('pointerdown', function(evt) {{
                    if (evt.button !== 0) return;
                    const currentThumb = _getThumb();
                    if (currentThumb && (evt.target === currentThumb || currentThumb.contains(evt.target))) return;
                    evt.preventDefault();
                    const index = _calcTargetIndex(evt.clientY);
                    _lastNavIndex = -1;
                    _navToIndex(index);
                }}, opts);
            }}

            // Position thumb on initial load
            _positionThumbFromState();
            _setupScrollbar();

            // After each HTMX settle, re-position thumb from updated hidden input
            document.body.addEventListener('htmx:afterSettle', function() {{
                if (!_isDragging) {{
                    _positionThumbFromState();
                    _setupScrollbar();
                }}
            }});
        }})();
    """
