"""JavaScript generator for custom scrollbar interaction (drag thumb, click track, position sync)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/js/scrollbar.ipynb.

# %% auto #0
__all__ = ['generate_scrollbar_js']

# %% ../../nbs/js/scrollbar.ipynb #b2c2780b
from ..core.models import ScrollbarIds

# %% ../../nbs/js/scrollbar.ipynb #323652be
def generate_scrollbar_js(
    ids: ScrollbarIds,           # Scrollbar HTML IDs (track, thumb)
    position_input_id: str,      # ID of hidden input (kept for API compat, not used for position sync)
    nav_url: str,                # URL to POST target index to
    nav_param: str = "target_index",  # Parameter name for the index value
    on_interact: str = "",       # JS callback name, called on user interaction start (drag/click)
) -> str:  # JavaScript IIFE code fragment
    """Generate JS for scrollbar: thumb positioning from track data + drag/click interaction."""
    _interact_js = (
        f"if (typeof window['{on_interact}'] === 'function') window['{on_interact}']();"
        if on_interact else ""
    )
    return f"""
        // === Virtual Scrollbar ({ids.prefix}) ===
        (function() {{
            // Pure server-authoritative drag model: pointer events compute a target index
            // and fire HTMX; the thumb visually moves only when the server's OOB swap lands
            // and _positionThumbFromState reads the fresh data attributes. No client-side
            // optimistic thumb movement — same single-source-of-truth model used for
            // keyboard nav in consumer libraries. Eliminates the "client paints, server
            // corrects" jitter that a hybrid model is subject to.
            let _isDragging = false;
            let _lastNavIndex = -1;

            function _getTrack() {{ return document.getElementById('{ids.track}'); }}
            function _getThumb() {{ return document.getElementById('{ids.thumb}'); }}

            function _isCursorMode(track) {{
                // Cursor-based mode: explicit thumb_ratio and max_position on track.
                // In this mode, the scrollbar always shows a proportional thumb
                // regardless of visible vs total item count.
                return track.dataset.thumbRatio !== undefined && track.dataset.maxPosition !== undefined;
            }}

            function _getMaxPosition(track) {{
                // Read max position from data attribute (set by server render).
                // Defaults to totalItems - visibleCount if not present.
                if (track.dataset.maxPosition !== undefined) {{
                    return parseInt(track.dataset.maxPosition);
                }}
                const totalItems = parseInt(track.dataset.totalItems || '0');
                const visibleCount = parseInt(track.dataset.visibleCount || '1');
                return Math.max(0, totalItems - visibleCount);
            }}

            function _getThumbHeightPct(track) {{
                // Compute thumb height as percentage. Uses data-thumb-ratio if present,
                // else falls back to visibleCount / totalItems.
                const totalItems = parseInt(track.dataset.totalItems || '0');
                const visibleCount = parseInt(track.dataset.visibleCount || '1');
                if (totalItems <= 0) return 100;

                let pct;
                if (track.dataset.thumbRatio !== undefined) {{
                    pct = parseFloat(track.dataset.thumbRatio) * 100;
                }} else {{
                    pct = (visibleCount / totalItems) * 100;
                }}

                // Enforce minimum thumb height
                if (track.offsetHeight > 0) {{
                    const minPct = (24 / track.offsetHeight) * 100;
                    pct = Math.max(pct, minPct);
                }} else {{
                    pct = Math.max(pct, 4);
                }}
                return pct;
            }}

            function _positionThumbFromState() {{
                // Read position from track's own data-position attribute.
                // The scrollbar track is OOB-updated with fresh data on every navigation,
                // making position sync self-contained (no dependency on external hidden inputs).
                const track = _getTrack();
                const thumb = _getThumb();
                if (!track || !thumb) return;

                const totalItems = parseInt(track.dataset.totalItems || '0');
                const visibleCount = parseInt(track.dataset.visibleCount || '1');
                const position = parseInt(track.dataset.position || '0');

                // In default (window) mode, all items visible means nothing to scroll.
                // In cursor mode (explicit thumb_ratio + max_position), always show
                // proportional thumb as a position indicator.
                if (totalItems <= 0 || (!_isCursorMode(track) && visibleCount >= totalItems)) {{
                    thumb.style.top = '0%';
                    thumb.style.height = '100%';
                    return;
                }}

                const thumbHeightPct = _getThumbHeightPct(track);
                const maxPos = Math.max(1, _getMaxPosition(track));
                const thumbTopPct = (position / maxPos) * (100 - thumbHeightPct);

                thumb.style.top = thumbTopPct.toFixed(2) + '%';
                thumb.style.height = thumbHeightPct.toFixed(2) + '%';
            }}

            function _calcTargetIndex(pointerY) {{
                const track = _getTrack();
                if (!track) return 0;
                const rect = track.getBoundingClientRect();
                const maxPos = Math.max(0, _getMaxPosition(track));
                const relY = Math.max(0, Math.min(pointerY - rect.top, rect.height));
                return Math.round((relY / rect.height) * maxPos);
            }}

            function _navToIndex(index) {{
                if (index === _lastNavIndex) return;  // Deduplicate
                _lastNavIndex = index;
                htmx.ajax('POST', '{nav_url}', {{
                    swap: 'none',
                    values: {{ {nav_param}: index }}
                }});
            }}

            // --- Document-level drag handlers ---

            function _onDragMove(evt) {{
                if (!_isDragging) return;
                evt.preventDefault();
                // Pure server-authoritative: translate cursor to index, fire HTMX.
                // The OOB response is what moves the thumb — no client-side paint here.
                const index = _calcTargetIndex(evt.clientY);
                _navToIndex(index);
            }}

            function _onDragEnd(evt) {{
                if (!_isDragging) return;
                _isDragging = false;
                _lastNavIndex = -1;
                document.removeEventListener('pointermove', _onDragMove);
                document.removeEventListener('pointerup', _onDragEnd);
                document.removeEventListener('pointercancel', _onDragEnd);
                const thumb = _getThumb();
                if (thumb) thumb.style.cursor = '';
                _setupScrollbar();
            }}

            function _setupScrollbar() {{
                const track = _getTrack();
                const thumb = _getThumb();
                if (!track || !thumb) return;

                if (track._scrollbarAbort) track._scrollbarAbort.abort();
                const controller = new AbortController();
                track._scrollbarAbort = controller;
                const opts = {{ signal: controller.signal }};

                // --- Thumb drag start ---
                thumb.addEventListener('pointerdown', function(evt) {{
                    if (evt.button !== 0) return;
                    evt.preventDefault();
                    evt.stopPropagation();
                    {_interact_js}
                    _isDragging = true;
                    _lastNavIndex = -1;
                    thumb.style.cursor = 'grabbing';
                    document.addEventListener('pointermove', _onDragMove);
                    document.addEventListener('pointerup', _onDragEnd);
                    document.addEventListener('pointercancel', _onDragEnd);
                }}, opts);

                // --- Track click (jump to position) ---
                track.addEventListener('pointerdown', function(evt) {{
                    if (evt.button !== 0) return;
                    const currentThumb = _getThumb();
                    if (currentThumb && (evt.target === currentThumb || currentThumb.contains(evt.target))) return;
                    evt.preventDefault();
                    {_interact_js}
                    const index = _calcTargetIndex(evt.clientY);
                    _lastNavIndex = -1;
                    _navToIndex(index);
                }}, opts);
            }}

            // Shared handler for htmx swap/settle events — syncs thumb from the fresh
            // server data attributes. Skip listener re-setup during drag so we don't
            // abort and replace the pointerdown listeners on a thumb that's mid-interaction
            // (document-level pointermove/pointerup are not affected either way).
            function _onHtmxMutation() {{
                _positionThumbFromState();
                if (!_isDragging) _setupScrollbar();
            }}

            // Position thumb on initial load
            _positionThumbFromState();
            _setupScrollbar();

            // Listen to both afterSwap (immediate) and afterSettle (safety net).
            document.body.addEventListener('htmx:afterSwap', _onHtmxMutation);
            document.body.addEventListener('htmx:afterSettle', _onHtmxMutation);
        }})();
    """
