"""Pure math functions for scrollbar thumb position and size calculation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/math.ipynb.

# %% auto #0
__all__ = ['compute_scrollbar']

# %% ../../nbs/core/math.ipynb #35d2f7ed
from typing import Tuple

# %% ../../nbs/core/math.ipynb #64188270
def compute_scrollbar(position: int,           # Current position (0-indexed)
                      visible_count: int,       # Number of visible items
                      total_items: int,          # Total item count
                      track_height: float,       # Scrollbar track height in px
                      min_thumb_height: int = 24,  # Minimum thumb height in px
                     ) -> Tuple[float, float]:   # (thumb_top_percent, thumb_height_percent)
    """Compute scrollbar thumb position and size as percentages."""
    if total_items <= 0 or visible_count >= total_items:
        return (0.0, 100.0)  # Thumb fills entire track

    # Thumb height as proportion of visible/total
    thumb_height_pct = (visible_count / total_items) * 100.0

    # Enforce minimum thumb height
    if track_height > 0:
        min_pct = (min_thumb_height / track_height) * 100.0
        thumb_height_pct = max(thumb_height_pct, min_pct)

    # Thumb position: proportion of position within scrollable range
    max_start = max(1, total_items - visible_count)
    thumb_top_pct = (position / max_start) * (100.0 - thumb_height_pct)

    return (thumb_top_pct, thumb_height_pct)
