"""Pure math functions for scrollbar thumb position and size calculation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/math.ipynb.

# %% auto #0
__all__ = ['compute_scrollbar']

# %% ../../nbs/core/math.ipynb #35d2f7ed
from typing import Optional, Tuple

# %% ../../nbs/core/math.ipynb #64188270
def compute_scrollbar(position: int,           # Current position (0-indexed)
                      visible_count: int,       # Number of visible items
                      total_items: int,          # Total item count
                      track_height: float,       # Scrollbar track height in px
                      min_thumb_height: int = 24,  # Minimum thumb height in px
                      max_position: Optional[int] = None,  # Upper bound of position range (None = total_items - visible_count)
                      thumb_ratio: Optional[float] = None,  # Thumb height as fraction of track (None = visible_count / total_items)
                     ) -> Tuple[float, float]:   # (thumb_top_percent, thumb_height_percent)
    """Compute scrollbar thumb position and size as percentages.

    When thumb_ratio and max_position are explicitly provided (cursor-based
    model), the thumb size and range are fully determined by those values
    regardless of the visible_count vs total_items relationship.
    """
    if total_items <= 0:
        return (0.0, 100.0)  # No items — thumb fills track

    # In default (window) mode, all items visible means nothing to scroll
    if thumb_ratio is None and max_position is None and visible_count >= total_items:
        return (0.0, 100.0)

    # Thumb height: use explicit ratio if provided, else visible/total
    if thumb_ratio is not None:
        thumb_height_pct = thumb_ratio * 100.0
    else:
        thumb_height_pct = (visible_count / total_items) * 100.0

    # Enforce minimum thumb height
    if track_height > 0:
        min_pct = (min_thumb_height / track_height) * 100.0
        thumb_height_pct = max(thumb_height_pct, min_pct)

    # Thumb position: proportion of position within scrollable range
    max_pos = max_position if max_position is not None else (total_items - visible_count)
    max_pos = max(1, max_pos)
    thumb_top_pct = (position / max_pos) * (100.0 - thumb_height_pct)

    return (thumb_top_pct, thumb_height_pct)
