"""Data models for scrollbar configuration, state, and HTML ID generation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/models.ipynb.

# %% auto #0
__all__ = ['ScrollbarConfig', 'ScrollbarState', 'ScrollbarIds']

# %% ../../nbs/core/models.ipynb #f2b36840
from dataclasses import dataclass
from typing import Optional

# %% ../../nbs/core/models.ipynb #39993167
@dataclass
class ScrollbarConfig:
    """Initialization-time configuration for a virtual scrollbar."""
    prefix: str = "sb"                  # HTML ID prefix
    show_scrollbar: bool = True          # Enable/disable scrollbar rendering
    min_thumb_height: int = 24           # Minimum thumb height in pixels
    track_width: int = 3                 # Track width in Tailwind units (w-3 = 12px)

# %% ../../nbs/core/models.ipynb #bad31c56
@dataclass
class ScrollbarState:
    """Mutable runtime state for a virtual scrollbar."""
    position: int = 0                              # Current position (0-indexed)
    visible_count: int = 1                         # Number of visible items
    total_items: int = 0                           # Total item count
    max_position: Optional[int] = None             # Upper bound of position range (None = total_items - visible_count)

# %% ../../nbs/core/models.ipynb #b73c24d4
@dataclass
class ScrollbarIds:
    """HTML element ID generators for a scrollbar instance."""
    prefix: str = "sb"  # Instance prefix

    @property
    def track(self) -> str: return f"{self.prefix}-scrollbar-track"  # Scrollbar track container

    @property
    def thumb(self) -> str: return f"{self.prefix}-scrollbar-thumb"  # Draggable thumb element
