"""Custom scrollbar component with proportional thumb for position indication."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/scrollbar.ipynb.

# %% auto #0
__all__ = ['render_scrollbar_thumb', 'render_scrollbar']

# %% ../../nbs/components/scrollbar.ipynb #638a6268
from fasthtml.common import Div

from cjm_fasthtml_tailwind.utilities.sizing import w
from cjm_fasthtml_tailwind.utilities.layout import position, display_tw
from cjm_fasthtml_tailwind.utilities.interactivity import cursor, select
from cjm_fasthtml_tailwind.core.base import combine_classes

from cjm_fasthtml_daisyui.utilities.semantic_colors import bg_dui
from cjm_fasthtml_daisyui.utilities.border_radius import border_radius

from ..core.models import ScrollbarConfig, ScrollbarState, ScrollbarIds
from ..core.math import compute_scrollbar

# %% ../../nbs/components/scrollbar.ipynb #d42ade07
def render_scrollbar_thumb(
    state: ScrollbarState,       # Scrollbar state
    config: ScrollbarConfig,     # Scrollbar config
    ids: ScrollbarIds,           # HTML IDs
    track_height: float = 600.0, # Track height for min thumb calculation
    oob: bool = False,           # Whether to include hx-swap-oob
) -> Div:  # Thumb element
    """Render the scrollbar thumb at the correct position."""
    thumb_top, thumb_height = compute_scrollbar(
        state.position, state.visible_count, state.total_items,
        track_height, config.min_thumb_height,
        max_position=state.max_position,
        thumb_ratio=state.thumb_ratio,
    )

    thumb = Div(
        id=ids.thumb,
        cls=combine_classes(
            position.absolute, w.full, border_radius.field,
            bg_dui.base_content.opacity(30),
            cursor.grab,
        ),
        style=f"top: {thumb_top:.2f}%; height: {thumb_height:.2f}%",
    )

    if oob:
        thumb.attrs["hx-swap-oob"] = "outerHTML"

    return thumb

# %% ../../nbs/components/scrollbar.ipynb #bb1f5a50
def _build_track_cls(track_width: int) -> str:  # Combined CSS class string
    """Build track CSS classes for a given width."""
    return combine_classes(
        w(track_width), position.relative, border_radius.field,
        bg_dui.base_content.opacity(10),
        cursor.pointer, select.none,
    )

# %% ../../nbs/components/scrollbar.ipynb #45ea740d
def render_scrollbar(
    state: ScrollbarState,       # Scrollbar state
    config: ScrollbarConfig,     # Scrollbar config
    ids: ScrollbarIds,           # HTML IDs
) -> Div:  # Complete scrollbar (track + thumb)
    """Render the custom scrollbar with track and proportional thumb."""
    # Hide track when all items visible, but keep element for consistent layout
    if state.total_items <= state.visible_count:
        return Div(id=ids.track, cls=str(display_tw.hidden))

    thumb = render_scrollbar_thumb(state, config, ids)

    # Compute effective max_position for JS to read
    max_pos = state.max_position if state.max_position is not None else (state.total_items - state.visible_count)

    # Build track attributes
    track_attrs = dict(
        data_total_items=str(state.total_items),
        data_visible_count=str(state.visible_count),
        data_max_position=str(max_pos),
    )

    # Optional thumb_ratio for JS (when not using default visible_count/total_items)
    if state.thumb_ratio is not None:
        track_attrs["data_thumb_ratio"] = f"{state.thumb_ratio:.6f}"

    return Div(
        thumb,
        id=ids.track,
        cls=_build_track_cls(config.track_width),
        **track_attrs,
    )
